name: publishImage
concurrency:
  group: ${{ github.event_name }}-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - master
permissions:
  actions: read
  contents: read
  packages: write
  pull-requests: write
jobs:
  publishImage:
    # if: ${{ (github.ref_name == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.event.repository.full_name }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
